<div id="workspace">
  <div class="row">
    <div class="col-12 mt-3">
      <h4>Lista de Cursos Matriculados</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-12 mt-3">
      <div class="card">
        <div class="card-horizontal">
          <div class="img-square-wrapper">
            <img class="" src="http://via.placeholder.com/300x180" alt="Card image cap">
          </div>
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <div class="form-group">
              <button id="btnVideos" class="btn btn-info pull-left" style="margin-top: 12px;" >
                <i class="fa fa-video-camera" style="margin-right:5px"></i>
                Videos del Curso
              </button>
            </div>
            <div class="form-group">
              <button id="btnManStudent"  class="btn btn-secondary pull-left" style="margin-top: 12px; margin-left: 20px;" > <i class="fa fa-book" style="margin-right:5px"></i>Materiales del Curso</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-12 mt-3">
      <div class="card">
        <div class="card-horizontal">
          <div class="img-square-wrapper">
            <img class="" src="http://via.placeholder.com/300x180" alt="Card image cap">
          </div>
          <div class="card-body">
            <h4 class="card-title">Card title</h4>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>