<!DOCTYPE html>
<html>
<head>
  <title><?php echo $title;?></title>
  <meta charset="UTF-8">
  <?php echo $csss; ?>
  <link rel="shortcut icon" href="<?php echo $constants['static_url']; ?>favicon.ico">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript">
    var BASE_URL = '<?php echo $constants['base_url'];?>';
    var STATIC_URL  = '<?php echo $constants['static_url'];?>';
    var CSRF = "<?php echo $constants['csrf']['secret']; ?>";
    var CSRF_KEY = '<?php echo $constants['csrf']['key']; ?>';
  </script>
</head>
<body>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary d-none" data-toggle="modal" data-target="#modal" id="btnModal">
    Launch demo modal
  </button>
  <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  </div>
  <!-- Header -->
  <header class="bg-primary fixed-top" id="nav1">
    <div class="container">
      <ul class="">
        <li class="">
          <a class="" href="/">Home</a>
        </li>
        <li class="">
          <a class="" href="/help">Ayuda</a>
        </li>
      </ul>
      <ul class="pull-right" style="float: right !important;">
        <li class="">
          Hola 
          <a class="" href="/user"><?php echo $_SESSION['student_names']; ?></a>
        </li>
        <li class="">
          <a class="" href="<?php echo $_SESSION['logout_url']; ?>">Salir</a>
        </li>
      </ul>
    </div>
  </header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-secondary fixed-top" id="nav2">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        Legis Juristas
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" id="burgerMenuButton">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <!--
            <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          -->
          <li class="nav-item">
            <a class="nav-link" href="/courses">Mis Cursos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/user/edit">Mis Datos</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
