<!DOCTYPE html>
<html>
<head>
  <title><?php echo $title;?></title>
  <meta charset="UTF-8">
  <?php echo $csss; ?>
  <link rel="shortcut icon" href="<?php echo $constants['static_url']; ?>favicon.ico">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript">
    var BASE_URL = '<?php echo $constants['base_url'];?>';
    var STATICS_URL  = '<?php echo $constants['static_url'];?>';
    var MODULOS_JSON = JSON.parse('<?php echo $menu; ?>');
    var ITEMS_JSON = JSON.parse('<?php echo $items; ?>');
    var DATA = JSON.parse('<?php echo $data; ?>');
    var CSRF = "<?php echo $constants['csrf']['secret']; ?>";
    var CSRF_KEY = '<?php echo $constants['csrf']['key']; ?>';
  </script>
</head>
<body>
  <label id="defaultTargetMensajes"></label>
  <!-- Inicio modal -->
  <button type="button" class="btn btn-primary btn-lg oculto" data-toggle="modal" data-target="#modal-container" data-backdrop="static"  data-backdrop="static" id="btnModal">Launch demo modal</button>
  <div class="modal fade" id="modal-container" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  <!-- Fin modal -->
  <div id="app">
    <header>
      <a href="<%= CONSTANTS[:base_url] %>">Inicio</a>
      <a href="<%= CONSTANTS[:base_url] %>ayuda">Ayuda</a>
      <a href="<%= CONSTANTS[:base_url] %>view" class="pull-right">Pepe Valdivia</a>
      <a href="<?php echo $_SESSION['logout_url']; ?>" class="pull-right">Cerrar Sesión</a>
    </header>
    <nav>
      <h1><i class="fa fa-futbol-o h1" aria-hidden="true"></i>Administración de Canchas</h1>
      <?php echo $modules; ?>
    </nav>
    <div id="body-app" class="row">
      <aside class="col-md-2">
        <?php echo $items; ?>
      </aside>
      <section class="col-md-10" id="workspace">
        <!-- Inicio Yield-->
