<form class="form-signin" action="/login" method="post">
    <img src="<?php echo $constants['static_url']; ?>assets/img/logo2.png" alt="" width="150" height="150">
    <input type="hidden" name="key" value="value">
    <span class="extraData"></span>
    <!--USER -->
    <label for="user" class="sr-only">User</label>
    <input type="text" id="user" class="form-control" placeholder="Usuario" required="" autofocus="" name="user">
    <!--CSRF -->
    <input type="hidden" name="<?php echo $constants['csrf']['key']; ?>" value="<?php echo $constants['csrf']['secret']; ?>">
    <!--PASS -->
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Contraseña" required="" name="password">
    <!--MESSAGE-->
    <p class="<?php echo $message_color; ?> message" style="margin-top:10px;" id="login-message"><?php echo $message; ?></p>
    <!--BUTTON -->
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Ingresar
    </button>
    <a class="btn btn-lg btn-success btn-block" style="margin-top: -14px; margin-bottom: 15px;" href="https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=1044701093820-jam7g5carn4nghkkhqr75ustq0l5vrum.apps.googleusercontent.com&redirect_uri=<?php echo $constants['base_url']; ?>oauth/callback?origin=google&scope=profile email">
      <i class="fa fa-google" aria-hidden="true"></i>
      Ingresar con Google
    </a>
    <!--FooTER LOGIN NAV -->
    <div class="link-login">
      <a class="" href="/login/sign_in">
        Registrarse
      </a>
      <a id="forgotpassword" class="pull-right" href="/login/reset">
        Olvidó su Contraseña
      </a>
    </div>
    <p class="mt-5 mb-3 text-muted">Powered By <a href="http://softweb.pe/"> Softtware Web Perú</a> © 2017-2018</p>
  </form>