<form class="form-signin" action="/login" method="post">
    <img src="<?php echo $constants['static_url']; ?>assets/img/logo2.png" alt="" width="150" height="150">
    <input type="hidden" name="key" value="value">
    <span class="extraData"></span>
    <!--EMAIL -->
    <label for="email" class="sr-only">Email</label>
    <input type="email" id="email" class="form-control" placeholder="Correo" required="" autofocus="" name="email">
    <!--CSRF -->
    <input type="hidden" name="<?php echo $constants['csrf']['secret']; ?>" value="<?php echo $constants['csrf']['key']; ?>">
    <!--MESSAGE-->
    <p class="<?php echo $message_color; ?> message" style="margin-top:10px;" id="login-message"><?php echo $message; ?></p>
    <!--BUTTON -->
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Recueperar Contraeña
    </button>
    <!--FooTER LOGIN NAV -->
    <div class="link-login">
      <a class="" href="/login/sign_in">
        Ingresar
      </a>
      <a id="forgotpassword" class="pull-right" href="/login/sign_in">
        Crear Cuenta
      </a>
    </div>
    <p class="mt-5 mb-3 text-muted">Powered By <a href="http://softweb.pe/"> Softtware Web Perú</a> © 2017-2018</p>
  </form>