<form class="form-signin" action="/login" method="post">
    <img src="<?php echo $constants['static_url']; ?>assets/img/logo2.png" alt="" width="150" height="150">
    <input type="hidden" name="key" value="value">
    <span class="extraData"></span>
    <!--USER -->
    <label for="email" class="sr-only">Email</label>
    <input type="email" id="email" class="form-control" placeholder="Correo" required="" autofocus="" name="email">
    <!--USER -->
    <label for="user" class="sr-only">Correo</label>
    <input type="text" id="user" class="form-control" placeholder="Usuario" required="" autofocus="" name="user">
    <!--CSRF -->
    <input type="hidden" name="<?php echo $constants['csrf']['secret']; ?>" value="<?php echo $constants['csrf']['key']; ?>">
    <!--PASS -->
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="inputPassword" class="form-control" placeholder="Contraseña" required="" name="password">
    <!--PASS 2-->
    <label for="inputPassword2" class="sr-only">Password</label>
    <input type="password" id="inputPassword2" class="form-control" placeholder="Repita su Contraseña" required="" name="password2">
    <!--MESSAGE-->
    <p class="<?php echo $message_color; ?> message" style="margin-top:10px;" id="login-message"><?php echo $message; ?></p>
    <!--BUTTON -->
    <button class="btn btn-lg btn-primary btn-block" type="submit">
      Crear Cuenta
    </button>
    <!--FooTER LOGIN NAV -->
    <div class="link-login">
      <a class="" href="/login">
        Ingresar
      </a>
      <a id="forgotpassword" class="pull-right" href="/login/reset">
        Olvidó su Contraseña
      </a>
    </div>
    <p class="mt-5 mb-3 text-muted">Powered By <a href="http://softweb.pe/"> Softtware Web Perú</a> © 2017-2018</p>
  </form>