<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="<?php echo $constants['static_url'];?>assets/img/logo.png" height="35" alt="CoolBrand">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Inicio</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/nostros">Nosotros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/capacitaciones">Capacitaciones</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/ponentes">Ponentes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/contacto">Contacto</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- Background video -->
<div class="video-background-holder">
  <div class="video-background-overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
        <source src="<?php echo $constants['static_url'];?>assets/videos/legis-juristas.mp4" type="video/mp4">
    </video>
  <div class="video-background-content container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="display-4">Bootstrap video background</h1>
        <p class="lead mb-0">With HTML5 Video and Bootstrap 4</p>
        <p class="lead">Snippet by <a href="https://bootstrapious.com/snippets" class="text-white">
                    <u>Bootstrapious</u></a>
        </p>
      </div>
    </div>
  </div>
</div>
<!-- End -->
<!-- For demo purpose -->
<section class="py-5">
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-8 mx-auto">
        <p class="lead">The whole content is wrapped into <code>.video-background-holder</code>, this class is mainly used to set the content dimensions, location and the fallback background in case the browser doesn't support the video format.</p>
        <p class="lead">Change your video source from <code>source</code> tag, and the overlay color from <code>.video-background-overlay</code>.</p>
        <p class="lead">The content text wrapped into <code>.video-background-content</code> is vertically centered using flex utilities.</p>
      </div>
    </div>
  </div>
</section>
<!-- End -->
