<!-- event modal -->
<div class="modal" tabindex="-1" role="dialog" id="eventModal"></div>
<!-- video modal -->
<div class="modal" tabindex="-1" role="dialog" id="videoModal">
<div class="modal-body">                   
  <div class="embed-responsive-item d-flex p-2 justify-content-center">
      <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop" class="embed-responsive-item" controls id="legisvideo"> 
        <!--<video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop"></video>-->
        <source src="<?php echo $constants['static_url'];?>assets/videos/legis-juristas.mp4" type="video/mp4">
      </video>
    </div>
  </div>
</div>
<!-- nav -->
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">
      <img src="<?php echo $constants['static_url'];?>assets/img/logo.png" height="55" alt="CoolBrand">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active" id="linkInicio">
          <a class="nav-link" href="/">Inicio</a>
        </li>
        <li class="nav-item" id="linkNosotros">
          <a class="nav-link" href="/nosotros">Nosotros</a>
        </li>
        <li class="nav-item" id="linkCapacitaciones">
          <a class="nav-link" href="/capacitaciones">Capacitaciones</a>
        </li>
        <li class="nav-item" id="linkPonentes">
          <a class="nav-link" href="/ponentes">Ponentes</a>
        </li>
        <li class="nav-item" id="linkContacto">
          <a class="nav-link" href="/contacto">Contacto</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Legis Juristas Escuela de Derecho</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 align-self-baseline">
        <p class="text-white-75 font-weight-light mb-5">Líderes en formación y desarrollo jurídico</p>
        <button class="btn btn-primary btn-xl js-scroll-trigger" onclick="showVideo(event)">Ver Video</button>
      </div>
    </div>
  </div>
</header>
<!-- End -->
<!-- partners -->
<section id="partners">
  <h2 class="section-title text-center">Nuestros Socios</h2>
  <hr class="separator">
  <div class="text-center">
    <img src="<?php echo $constants['static_url'];?>assets/img/cal.png" height="75">
    <img src="<?php echo $constants['static_url'];?>assets/img/ccl.png" height="80" style="margin-left:100px;">
  </div>
</section>
<!-- AboutUs -->
<section id="about">
  <h2 class="section-title text-center">Nosotros</h2>
  <hr class="separator">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="text-center">
          <img src="<?php echo $constants['static_url'];?>assets/img/about.png" heigth="280" width="280" alt="CoolBrand">
        </div>
      </div>
      <div class="col-md-6 text-about">
        <p>Somos una empresa dedicada a la capacitación y difusión de temas relacionados a las ciencias jurídicas, líderes en la organización de: Diplomados, seminarios, cursos de alta especialización, seminarios, talleres, asesoramiento para optar el título de abogado y más..</p>
      </div>
    </div>
  </div>
</section>
<!-- events -->
<section class="container" id="events"> 
  <h2 class="section-title text-center">Nuestros Cursos y Diplomados</h2>
  <hr class="separator">
  <h3 class="section-subtitle">Nuestro Proximo Evento</h3>
  <div class="row" id="rowNextEvents">
  </div>
  <h3 class="section-subtitle margin-extra-subtitle">Ponemos a su Disposicion Nuestros Cursos y Diplomados de Alta Especialización</h3>
  <div class="row">
    <div class="col-md-12">
      <div class="form-inline" id="rowEventsFilters">
        <label>Especilidad</label>
        <select class="form-control" id="sclSpecialism">
        </select>
        <label>Categoría</label>
        <select class="form-control" id="sclType">
          <option value="E">Todos</option>
          <option value="1">Curso</option>
          <option value="2">Diplomado</option>
        </select>            
        <button class="btn btn-primary" type="button" tabindex="-1" onclick="searchEvents(event)" id="bthSearch">
          <i class="fa fa-search" aria-hidden="true"></i>
          Buscar
        </button>
      </div>
    </div>
  </div>
  <div class="row" id="events-row">
  </div>
  <div class="row">
    <div class="col-md-12">
      <nav aria-label="Page navigation example">
        <ul class="pagination pull-right" id="paginationEvents">
        </ul>
      </nav>
    </div>
  </div>
</section>
<!-- speakers -->
<section id="speakers">
  <div class="container">
    <h2 class="section-title text-center">Algunos de Nuestros Ilustres Ponentes</h2>
    <hr class="separator">
    <div id="speakers-row">
    </div>
  </div>
</section>
<!-- footer -->
<div class="footer-social">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        Síguenos en nuestras redes sociales
      </div>
      <div class="col-md-6">
        <a href="https://www.facebook.com/LegisJuristasEscuelaDeDerecho/" class="social-link pull-right">
          <i class="fa fa-facebook-official" aria-hidden="true"></i>
        </a>
        <a href="https://www.instagram.com/legis_juristas/" class="social-link pull-right">
          <i class="fa fa-instagram" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
</div>
<footer>
  <div class="footer-above">
    <div class="container">
      <div class="row" id="contact">
        <div class="footer-col col-md-4">
          <h2>Contacto</h2>
          <p id="messageForm"></p>
          <div class="form-group">
            <label for="txtName">Nombre</label>
            <input type="text" class="form-control" id="txtName" placeholder="Ingrese su nombre">
          </div>
          <div class="form-group">
            <label for="txtEmail">Correo</label>
            <input type="email" class="form-control" id="txtEmail" placeholder="Ingrese su correo">
          </div>
        </div>
        <div class="footer-col col-md-4">
          <div class="form-group">
            <label for="txtMessage">Mensaje</label>
            <textarea class="form-control" id="txtMessage" rows="6"></textarea>
          </div>
          <button type="button" class="btn btn-primary btn-lg btn-block" id="btnContact" onclick="sendEmail(event)">Enviar</button>
        </div>
        <div class="footer-col col-md-4">
        <div class="contact-info">
					<div class="info-item">
						<i class="fa fa-home" aria-hidden="true"></i>
						<h6>Jr. Mariano de los Santos 109</h6>
						<p>Barranco</p>
					</div>
          <div class="contact-info">
            <div class="info-item">
              <i class="fa fa-whatsapp" aria-hidden="true"></i>
              <h6>+51 997 139 531</h6>
			  <br>
            </div>
          </div>
          <div class="contact-info">
            <div class="info-item">
              <i class="fa fa-envelope-o" aria-hidden="true"></i>
              <h6>info@legisjuristas.com</h6>
              <p>Mándanos tus consultas!</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </div>
  <div class="footer-below">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          © 2020 Legis Juristas - Derechos Reservados&nbsp; - &nbsp;<a class="primary-color" href="http://softweb.pe/website/"> Sitio Desarollado por Software Web Perú ©</a>
        </div>
      </div>
    </div>
  </div>
</footer>
<!-- floating action button -->
<a href="https://api.whatsapp.com/send?phone=51997139531&text=Consulta desde la web" class="float" target="_blank">
  <i class="fa fa-whatsapp my-float"></i>
</a>
